kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: database
spec:
  resources:
    requests:
      storage: 1Gi
  dataSource:
    name: my-volume
    kind: PersistentVolume
  accessModes:
    - ReadWriteOnce
